openapi: 3.1.0
info:
  title: Ping API
  description: Ping API
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /ping:
    get:
      summary: Vérifie la disponibilité du service
      responses:
        '200':
          description: Retourne pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
  
