openapi: 3.0.3
info:
  title: Products API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Recherche de produits
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        '200':
          description: Liste des produits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multiple:
                  summary: Plusieurs produits
                  value:
                    - name: "Pomme"
                      expiration_datetime: "2025-09-01T10:00:00Z"
                      price: 1.5
                    - name: "Banane"
                      expiration_datetime: "2025-09-05T10:00:00Z"
                      price: 2.0
                empty:
                  summary: Aucun produit
                  value: []
components:
  parameters:
    limit:
      name: limit
      in: query
      schema:
        type: integer
      example: 10
    q:
      name: q
      in: query
      schema:
        type: string
      example: "fruit"
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
