openapi: 3.0.3
info:
  title: Products & Orders API
  version: 1.0.0
tags:
  - name: Products
    description: Gestion des produits
  - name: Orders
    description: Gestion des commandes
paths:
  /products:
    get:
      tags: [Products]
      summary: Liste des produits
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        '200':
          description: Liste des produits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /orders:
    get:
      tags: [Orders]
      summary: Liste paginée des commandes
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          description: Liste des commandes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags: [Orders]
      summary: Créer une commande
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            example:
              identifier: 123
              customer_name: "Alice"
              creation_datetime: "2025-08-21T10:00:00Z"
              total_amount: 250.75
      responses:
        '201':
          description: Commande créée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  parameters:
    page:
      name: page
      in: query
      schema:
        type: integer
      example: 1
    size:
      name: size
      in: query
      schema:
        type: integer
      example: 20
    limit:
      name: limit
      in: query
      schema:
        type: integer
      example: 10
    q:
      name: q
      in: query
      schema:
        type: string
      example: "fruit"
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
    Order:
      type: object
      properties:
        identifier:
          type: integer
        customer_name:
          type: string
        creation_datetime:
          type: string
          format: date-time
        total_amount:
          type: number
          format: float
